### PR TITLE
Support patch, put, and delete methods

### LINKED ISSUE #34: PATCH, PUT, DELETE methods should be supported properly or should error
See comment in PR #33 https://github.com/sul-dlss/preservation-client/pull/33#discussion_r372144683 

We know PATCH is used for update-catalog requests for objects that aren't at the first version.

### PR DESCRIPTION
**Pull request by mjgiarlo**
Fixes #34

## Why was this change made?

Follows a suggestion by @jcoyne in #33.

## Was the documentation (README, API, wiki, consul, etc.) updated?

no

### CODE REVIEW

**Comment by julianmorley** [comment]
What can be deleted using this delete action?

**Comment by mjgiarlo** [comment]
@julianmorley Nothing at the moment. No API actions use the method. This is setting up API machinery for when it's needed, and being consistent across the API machinery.

**Comment by julianmorley** [comment]
@mjgiarlo Thanks, gtk. Please remember that if this does get implemented, we have a policy of not allowing remote delete of content from preservation.

**Comment by mjgiarlo** [comment]
@julianmorley OK. The preservation-client gem is a set of Ruby bindings for the HTTP API exposed by preservation_catalog, so until there's something in prescat's [routes](https://github.com/sul-dlss/preservation_catalog/blob/master/config/routes.rb#L10-L23) that support delete, we won't see anything in the client. I'm not aware of any tickets to do this.

**Pull request merged**
