### PR TITLE
Add a method for sending an update to the catalog endpoint

### PR DESCRIPTION
**Pull request by jcoyne**
## Why was this change made?

So that the preservation_robots can use the client to access the  update API

## Was the documentation (README, API, wiki, consul, etc.) updated?
yes.

### CODE REVIEW

**Comment by jcoyne** [comment]
@julianmorley I'm trying to port over what we're already doing here: https://github.com/sul-dlss/preservation_robots/blob/master/lib/robots/sdr_repo/preservation_ingest/update_catalog.rb#L31

**Comment by jcoyne** [comment]
@julianmorley it looks like the catalog endpoint expects the size: https://github.com/sul-dlss/preservation_catalog/blob/5b33514de00bcc2928ee267bc669b445cb57ede5/app/controllers/catalog_controller.rb#L64

**Comment by julianmorley** [comment]
> @julianmorley it looks like the catalog endpoint expects the size: https://github.com/sul-dlss/preservation_catalog/blob/5b33514de00bcc2928ee267bc669b445cb57ede5/app/controllers/catalog_controller.rb#L64

Ugh, wwwwhhhhhy? I don't think it does anything with that information. And shouldn't, even.

**Comment by ndushay** [comment]
It was to avoid unnec re-computations when we already knew the size.

**Comment by julianmorley** [comment]
> @julianmorley It was to avoid unnec re-computations when we already knew the size. IIRC, the size was meant to serve as an approximate thing to have some way to know how much was on a storage root, and stuff like that.

@ndushay ...but we don't use it, right? At all? Version size is in versionMetadata.xml if we need it without doing a 'du' on the directory, and that's the canonical value for the version. This just seems like we have a required parameter that's a) not used and b) not the actual source of truth for that information.

**Comment by jmartin-sul** [comment]
@julianmorley the thinking was that it's nice to be able to use size in query conditions and results.  as @ndushay says, it's an approximation.  but indeed, i'm unaware of anything in the codebase that uses the field.

**Pull request merged**
